sbatch -N 32 submit-batch-wo-node.sh --nthreads 2 --pthreads 2
sbatch -N 32 submit-batch-wo-node.sh --nthreads 2 --pthreads 2
sbatch -N 32 submit-batch-wo-node.sh --nthreads 2 --pthreads 2
sbatch -N 32 submit-batch-wo-node.sh --nthreads 2 --pthreads 2
sbatch -N 32 submit-batch-wo-node.sh --nthreads 4 --pthreads 4
sbatch -N 32 submit-batch-wo-node.sh --nthreads 4 --pthreads 4
sbatch -N 32 submit-batch-wo-node.sh --nthreads 4 --pthreads 4
sbatch -N 32 submit-batch-wo-node.sh --nthreads 4 --pthreads 4
sbatch -N 32 submit-batch-wo-node.sh --nthreads 8 --pthreads 8
sbatch -N 32 submit-batch-wo-node.sh --nthreads 8 --pthreads 8
sbatch -N 32 submit-batch-wo-node.sh --nthreads 8 --pthreads 8
sbatch -N 32 submit-batch-wo-node.sh --nthreads 8 --pthreads 8
sbatch -N 32 submit-batch-wo-node.sh --nthreads 8 --pthreads 4
sbatch -N 32 submit-batch-wo-node.sh --nthreads 4 --pthreads 8
sbatch -N 32 submit-batch-wo-node.sh --nthreads 16 --pthreads 2
sbatch -N 32 submit-batch-wo-node.sh --nthreads 2 --pthreads 16
sbatch -N 32 submit-batch-wo-node.sh --nthreads 2 --pthreads 8
sbatch -N 32 submit-batch-wo-node.sh --nthreads 8 --pthreads 2
